### ISSUE TITLE
envFrom structure requires additional YAML layer that does NOT render

### ISSUE THREAD

**Issue by needleshaped** [vidispine/hull#335] opened 2024-09-20 13:18 UTC
Thank you for the software! 
Use case I see often is loading variables from ConfigMap.

1. **Question**: why HULL requires additional YAML layer (`some-name-that-never-renders` in below example), e.g.:

    ```yml
                  envFrom:
                    some-name-that-never-renders:
                      configMapRef:
                        name: myconfigmap
    ```
    which doesn't even render:
    ```yml
          - envFrom:
            - configMapRef:
                name: myconfigmap
    ```
    Wasn't the goal to strictly follow Kubernetes structure? Is this a bug maybe?

2. **Request**: add a configuration **example** either to `hull-demo` or [/examples](https://github.com/vidispine/hull/tree/main/hull/files/examples) 

    Otherwise the only source of information was a test:
    https://github.com/vidispine/hull/blob/main/hull/files/test/HULL/sources/cases/statefulset/values.hull.yaml#L241

**Comment by gre9ory** [comment] 2024-09-20 19:26
> Thank you for the software!
Thank you for your interest!

**Comment by gre9ory** [comment] 2024-09-20 20:24
Hello @needleshaped,

> Thank you for the software!

Thank you for your interest in it!

Regarding your questions;

> Question: why HULL requires additional YAML layer (some-name-that-never-renders in below example), e.g.:

The goal of HULL was to provide out-of-the-box configurability of Kubernetes objects by making it possible to set every possible property for the objects that HULL supports. For the most part this is achieved by adhering to the Kubernetes JSON schema which provides the rails in which you can set properties, thereby sticking close to Kubernetes syntax.

For some properties however, HULL provides a dedicated and purposeful handling with the aim to improve the configuration side. For example, the `image` field in HULL's `containers` and `initContainers` is split into three properties `registry`, `repository` and `tag`. This enables features such as global definition of a `registry` for all your images which is then applied to each Kubernetes YAML `image` property as a prefix.

Other selected properties such as `envFrom` have a different twist: they are dictionaries on the HULL side and are converted to arrays on the Kubernetes side. The benefit of this is that a dictionary collection adds possibilities for later manipulation that arrays in Helm do not offer:

- overwrite selected values without changing the remaining items --> done by changing the value of the selected key in the dictionary 
- add to collection of values without dealing with what is already in there --> done by adding new key-value pair
- removing dedicated elements --> done by setting `enabled: false` in the property value dict

All of this is not possible with arrays that are defined in a `values.yaml`. If you want to change, add or delete the array, you __always__ need to completely overwrite it. What's worse, consider an array with elements that contain a lot of nesting. Even if you want to change something at the leaf of such an arrays YAML tree, you are forced to recreate the whole array in your `values.yaml` override file. In turn, this raises severe concerns about configuration drifts if you consider the case where you have overwritten such a complex array in your overlay `values.yaml` and the source `array` changes during a Helm chart version update. You may not even notice that the source array has changed and the application may start to misbehave. There is just a lot of issues associated with using arrays in Helm `values.yaml` which I consider to be one of the biggest weaknesses of regular Helm. 

Here is a hopefully complete list of these HULL-sided dictionaries which convert to arrays on the Kubernetes side:

- `initContainers`, `containers`, `volumes` in `cronjob`,`daemonset`, `deployment`, `job` and `statefulset` `pod` objects
- `ports`, `env`, `envFrom` and `volumeMounts` in `initContainers`, `containers` 
- `volumes` in `cronjob`,`daemonset`, `deployment`, `job` and `statefulset` `pod` objects
- `ports` in `service` objects
- `rules` and `tls` in `ingress` objects
- `http.paths` in `rules` in `ingress` objects
- `webhooks` in `validatingwebhookconfiguration` and `mutatingwebhookconfiguration`
- `rules` in `clusterrole` and `role`

More information on these properties can be found in the table here for [HULL properties](https://github.com/vidispine/hull#composing-objects-with-hull) and the links that point to more details from there.

For some of the properties listed above, the keys in the dictionary additionally serve as the unique object keys in the case such a key exists on the Kubernetes side for the array elements. For example, the key in `ports` in a HULL spec: 

```
hull:
  objects:
    service:
      my-app-service:
        ports:
          my-app-http:
            protocol: TCP
            port: 80
            targetPort: http-web-svc
```            
maps directly to the `name` in the resulting service spec:

```
spec:
  ports:
  - name: my-app-http
    protocol: TCP
    port: 80
    targetPort: http-web-svc
```

In the same vein, `container` dicitionary keys map to the `container.name` and so on. In some cases, the key does not map to such a unique identifier property (as with `envFrom` keys) and the dictionary style only provides the described merging support. I suppose that is maybe the main reason for your question.

Hope this explains it sufficiently, let me know if something is unclear.

_Note that Kubernetes has a solution to this problem. In the Kubernetes JSON schema you have `merge-key` attributes on arrays which allow to target dedicated entries in the array for merging or deleting and so on. Helm has no concept for fine-grained array manipulation._

> Request: add a configuration example either to hull-demo or [/examples](https://github.com/vidispine/hull/tree/main/hull/files/examples)

Guilty as charged. I need to add more examples of HULL based `values.yaml`s, I do have a lot of real-life examples lying around. Will try to add them soon to the `files/examples`.

`hull-demo` is under a hundred lines by design. The idea was to not overburden visitors with long YAML but to show how much YAML content can be rendered with little input. For more details, the documentation, `files/examples` and to some degree test cases are provided.

**Comment by gre9ory** [comment] 2024-09-30 08:22
Closing this, please reopen or create a new issues if questions or problems remain. Thanks!

**Comment by needleshaped** [comment] 2024-10-01 07:36
Dear @gre9ory, thank you very much for the response. 

You have a extensive documentation across project, and your answers are on par, very detailed.
I thought it was a copy-paste from some documentation chapter, but it is NOT. 

It actually deserves separate chapter in documentation, though maybe too big for Chart Architecture document (where "objects with individual templates" are mentioned).

Also, I would argue that you want to close this issue, when examples are added.

P.S. I will create new ticket with few suggestions on how to help your project, coming from person with fresh perspective.

**Comment by gre9ory** [comment] 2024-10-01 08:17
You are right, after having closed the issue I had the after thought that I should have kept it open until examples are available :) It will be very soon though, I am working on a new release at the moment and will include a set of real life `values.yaml`s.

Very appreciated if you have thoughts on improvements, be it on the technical or documentation side. If I'd had unlimited time and resources, I would like to put more time into the documentation structure. Contentwise I think it contains everything I think that is required, but structuring and presenting it in the right way is certainly not easy! Your initial question is document to that. 

To sort of compensate, I like to take the time to write detailed answers to problems raised, this offers the chance to rethink what is documented and maybe try to add to it by reapproaching from the perspective of the user who got stuck.

I am eager to see your ideas on things, thank you.

**Comment by gre9ory** [comment] 2024-10-08 06:11
Now with latest releases more examples of `values.yaml` files based on HULL are available. 

Closing.

**Closed by gre9ory** 2024-10-08 06:11 UTC
